# Defining App builder image
FROM public.ecr.aws/docker/library/golang:1.22.4-alpine3.20 AS builder
RUN apk update; \
    apk add --no-cache \
    git
WORKDIR /app
ENV GO111MODULE=on
ARG NETRC_USER
ARG NETRC_TOKEN
RUN echo -e "machine example.com\nlogin $NETRC_USER\npassword $NETRC_TOKEN\n" > ~/.netrc
RUN chmod 600 ~/.netrc
RUN go env -w GOPRIVATE=example.com/*
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -v -trimpath -o .bin/example ./cmd/main.go
# ensure ~/.netrc is removed
RUN rm ~/.netrc

FROM public.ecr.aws/docker/library/alpine:3.20 as release
RUN apk add --no-cache --update ca-certificates curl
RUN adduser --disabled-password --gecos "" --shell "/sbin/nologin" --home "/nonexistent" --no-create-home --uid 10014 "app"
COPY --from=builder /app/.bin/example /app/cmd/
USER 10014
WORKDIR /app
CMD ["cmd/example","start"]
